### ISSUE TITLE
pmcli for free users.

### ISSUE THREAD

**Issue by 68656c6c** [christopher-dG/pmcli#13]
I would glady use the Google Play services only for uploading my music and listening to it, and that would be pretty rad if I could do it through the terminal, so if you mind, I would glady use pmcli in a state of only songs purchased and songs uploaded myself. :)

**Comment by christopher-dG** [comment]
I'm actually working on it in right now, it should be ready by the end of the day. I'll let you know, and maybe you can help me test it (I only have a couple of songs uploaded for testing, I'd like to see how it performs on larger libraries). 

Edit: I took a very good , long nap tonight so it'll be sometime this week instead :slightly_smiling_face:

**Comment by 68656c6c** [comment]
I wouldn't mind helping you test it at all, I have a lot of music uploaded to Google Play, and of course, take your time.

**Comment by christopher-dG** [comment]
@MeowMeowKins [develop](https://github.com/christopher-dg/pmcli/tree/develop) now has functionality for free users :slightly_smiling_face: 

If you don't mind testing it, I'd love to know how long it takes to generate your library when you first run the program. And of course I want to hear about all the things that break (there will probably be plenty).

**Comment by jackkinsey** [comment]
My library of 2001 songs generated in probably less time than it took to login--so, seconds. I had a crash when `pmcli` didn't find the `~/.local/share/pmcli/songs directory`, but a quick `mkdir` took care of that, and everything seems to be working fine now.

**Comment by christopher-dG** [comment]
That will be added to the install script :+1:

**Comment by christopher-dG** [comment]
Okay, the big new update is in develop and most things should be  working. #15 and #16 should be fixed, @jackkinsey can you confirm that those bits are working okay? The 'now playing' output behaviour is somewhat broken, but I'll fix that tonight.

**Comment by jackkinsey** [comment]
@christopher-dG #15 and #16 are both fixed for me in master. Good stuff!
