### ISSUE TITLE
`queue` command doesn't sanitize arguments

### ISSUE THREAD

**Issue by jackkinsey** [christopher-dG/pmcli#15]
_Using `develop` branch._
Running `q 03 04` got me a crash with the exception being a `ValueError` from an `int()` call. 
Side note: being able to queue multiple songs at once (as I tried here), or queue a range (say, `q 01-09`) of values, would be useful.

**Comment by christopher-dG** [comment]
This fix will be committed soon, I reorganized most things and now both free and full clients use the same queue function (the one for paid accounts already has the `q 1 2 3` functionality). Just getting one last thing sorted out.
