### ISSUE TITLE
pmcli crashes when trying to play songs with '/' in the title

### ISSUE THREAD

**Issue by jackkinsey** [christopher-dG/pmcli#16]
_Using `develop` branch._
Tries to download the song and put it in `~/.local/share/pmcli/songs`, but due to the unescaped '/' ends up attempting to use a subdirectory that doesn't exist.

**Comment by christopher-dG** [comment]
Hmm, this is weird to fix because you can't escape '/' characters in filenames -- they're just not allowed period. I guess I'll replace the character with some unicode or something when saving, and do a replacement when displaying the name. Thanks for the heads up!
