### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Redcroft** [christopher-dG/pmcli#22]
Hi,
downloaded the latest version and im getting this error

  File "/usr/local/bin/pmcli", line 6, in <module>
    from music_objects import Song, Artist, Album, Queue

Previous to updating it did work

**Comment by christopher-dG** [comment]
What branch are you on? 

e: I don't think that `from x import y` line is in the current code of either branch

**Comment by Redcroft** [comment]
I was on the current master branch, i had to uninstall then reinstall but not it works great, thanks
