### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by ihabunek** [christopher-dG/pmcli#23]
Any chance of adding this project to [PyPI](https://pypi.python.org/pypi)? I'd rather `pip install pmcli` then worry about dependencies manually.

There's a pretty good how-to here:
https://packaging.python.org/distributing/

**Comment by christopher-dG** [comment]
I've tried a few times but always run into problems, this is a PR that I'd be thrilled to see though.

**Comment by ihabunek** [comment]
I'll see how my weekend goes. :)

**Comment by christopher-dG** [comment]
If you do, do it off of develop branch please 👍 

e: I came very close to accidentally deleting my entire project, and as a result the develop branch no longer exists

**Comment by matteing** [comment]
I started working on this today, and it basically requires restructuring the whole thing. I'm working on making this less breaking.

**Comment by christopher-dG** [comment]
Yeah that's precisely why I haven't done it already, it's not nearly as simple as it should be because my code is spaghetti haha. Thanks for your efforts, if you can't get it working, don't fret!

**Comment by matteing** [comment]
I got it working though :p will submit a pull soon. 

EDIT:
Okay, help me test this :p

```
pip install gpymusic
$ gpymusic-setup
$ gpymusic
```
