### ISSUE TITLE
Any way of hooking up play/pause media key?

### ISSUE THREAD

**Issue by jacklenox** [christopher-dG/pmcli#32]
This might be a long shot, but is there any way it might be possible to allow users to use keyboard media keys with this client? I'm using Ubuntu and have a Play/Pause key on my laptop. It would be great to not have to tab to gpymusic to play/pause music.

**Comment by christopher-dG** [comment]
This just needs to be configured in mpv, check out [the docs](https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst) for some general info. When I get home I'll add my specific config.

**Comment by christopher-dG** [comment]
My setup is as follows:

i3 config (any keybinding program will work for this):

```
bindsym XF86AudioPause exec --no-startup-id echo "cycle pause" > ~/.config/mpv/control
bindsym XF86AudioNext exec --no-startup-id echo "playlist-next" > ~/.config/mpv/control
bindsym XF86AudioPrev exec --no-startup-id echo "playlist-prev" > ~/.config/mpv/control
```

mpv config:

```
input-file=~/.config/mpv/control
```

`control` is a fifo pipe (`mkfifo`). Seeking backwards doesn't work, and that is an issue with my code but the rest should work fine.

**Comment by jacklenox** [comment]
Thank you so much for your response and for helping here. Due to my own density/lack of understanding, it took me a while to work out exactly what you were suggesting I do. So, for anyone following in my wake who might fall upon this, and is a n00b like me, here's what I did on Ubuntu 16.04 to get this working like a charm.

In `~/.config/mpv/`:

```
mkfifo control
```

This creates the fifo pipe.

Something that is, in retrospect, totally obvious, however not obvious enough for me from scanning the mpv docs: you need to create a `config` file in the same directory as above.

So you'll have `~/.config/mpv/config`, and it'll contain:

```
input-file=~/.config/mpv/control
```

Finally, I wasn't sure how easily I'd get i3 to play nicely with Ubuntu, and after a bit of searching I came across [XBindKeys](http://www.nongnu.org/xbindkeys/xbindkeys.html).

You can install it with:

```
sudo apt install xbindkeys
```

There are instructions [here](http://www.nongnu.org/xbindkeys/xbindkeys.html#configuration) on configuring a default setup.

And finally, the vital two lines for me to add in `~/.xbindkeysrc` were:

```
"exec echo 'cycle pause' > ~/.config/mpv/control"
  XF86AudioPlay
```

I had to log out and back in again, and now the whole thing is working like a charm.

**Comment by christopher-dG** [comment]
Glad it's working. Thanks for the detailed instructions!
