### ISSUE TITLE
Crash during search, Ubuntu 16

### ISSUE THREAD

**Issue by cayce-crane** [christopher-dG/pmcli#42]
I installed gpymusic on Ubuntu 16.04. As far as I can tell, all my dependencies are up to date and I don't have anything wacky going on, but gpymusic crashes when I try to search for anything. Here's the traceback:

```
Traceback (most recent call last):
File "/home/dcrane/.local/bin/gpymusic", line 28, in <module>
common.client.transition()
File "/home/dcrane/.local/lib/python3.5/site-packages/gpymusic/client.py", line 57, in transition
 commands[command](arg)
 File "/home/dcrane/.local/lib/python3.5/site-packages/gpymusic/client.py", line 402, in search
 limit = common.w.main.ylimit - 4
AttributeError: '_curses.curses window' object has no attribute 'ylimit'

```

I have a free Google Play Music account, not a paid one, which I know may make a difference.

**Comment by christopher-dG** [comment]
Looks like it was just a careless mistake on my part. Can you try installing from master now?

**Comment by cayce-crane** [comment]
Works perfectly, thank you for the fix! Much appreciated.

**Comment by christopher-dG** [comment]
Great! The new version can be installed from PyPi now.
