### ISSUE TITLE
Audio fails to play; songs end immediately

### ISSUE THREAD

**Issue by kroppt** [christopher-dG/pmcli#48]
I tried individual songs and a queue of many, and each time, when a song plays, it pretty instantly finishes. It goes through each one until the queue is done playing within a few seconds. I do have the dependencies:
```
$ pip list | grep gpymusic
gpymusic (1.2.1)
$ python --version
Python 3.4.5
$ mpv --version
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.6
```

**Comment by christopher-dG** [comment]
Not quite sure why this would happen. One place to start would probably be using `gmusicapi` by itself to get a song URL, feeding it to `mpv` and seeing what happens.

**Comment by kroppt** [comment]
I was able to download a song to a file and test it. It works.

**Comment by christopher-dG** [comment]
And if you pass the URL straight to `mpv`?

**Comment by kroppt** [comment]
That helped me fix it. `ffmpeg` needed `openssl` support for handling HTTPS URLs.

Thanks.
