### ISSUE TITLE
Search not working with free account

### ISSUE THREAD

**Issue by christopher-dG** [christopher-dG/pmcli#5]
From the [gmusicapi docs](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.search):
>Free account search is restricted so may not contain hits for all result types.

After some investigation, the restricted content is values for keys 'album_hits', 'artist_hits', 'playlist_hits', 'situation_hits', and 'song_hits' `pmcli.search()`Uses 'song_hits', 'artist_hits', and 'album_hits' to generate results, so naturally it's unsuccessful.

I don't really have a solution for this, other than making free users only capable of radio stations. It's something that needs to be worked on in gmusicapi. If anyone has thoughts on how to work around this, I'd love to hear them.

**Comment by jackkinsey** [comment]
Some testing with gmusicapi confirmed for me that free accounts can use `Mobileclient.get_all_songs`, so I guess you could use that to build a local library index and then implement search locally? Would almost definitely mean a performance hit, especially considering the time it would take to load the library file on launch (mine is ~2 MB for a ~2,000 song library), but I suppose it's better than the thing just not working for free users.

**Comment by christopher-dG** [comment]
Yeah, I think this is really the only good option.
