### ISSUE TITLE
ConfigParser Requirement

### ISSUE THREAD

**Issue by kariudo** [christopher-dG/pmcli#6]
Might be worth nothing that ConfigParser module is also required.

**Comment by christopher-dG** [comment]
What is your Python version? On a fresh 3.6 virtualenv this is not the case.

**Comment by kariudo** [comment]
Using a 3.6.0 virtualenv

**Comment by christopher-dG** [comment]
Very weird, in that case I'll probably just parse the config manually to drop the dependency. Thanks!

**Comment by christopher-dG** [comment]
configparser is no longer required :slightly_smiling_face:
