### ISSUE TITLE
Add additional instructions to Readme

### ISSUE THREAD

**Issue by eightseventhreethree** [christopher-dG/pmcli#8]
Due to many users having both Python 2 and Python 3 I want to add some additional instructions.

**Comment by eightseventhreethree** [comment]
Also please let me commit :)

**Comment by christopher-dG** [comment]
To contribute:
- fork the repo
- checkout a new branch
- make your changes
- commit/push to your branch
- open a pull request to merge your branch into master

For now, I prefer not to give anyone else collaborator access, especially just for little readme changes. Thanks!
